import streamlit as st
import os
import sys
import glob
from datetime import datetime

# Add root dir to path
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)

from web.theme import load_custom_css

# Page Configuration
st.set_page_config(
    page_title="Neural Shield AI - Reports Database",
    layout="wide",
    page_icon="📄"
)

# Load global CSS styling
load_custom_css()

# Sidebar branding
from web.theme import apply_sidebar_branding
apply_sidebar_branding()

# Header Section
st.markdown("""
<div style="padding: 20px 0 10px 0;">
    <span style="font-size: 0.85rem; color: #6366f1; font-weight: 600; letter-spacing: 0.1em; text-transform: uppercase;">Electronic Health Records</span>
    <h1 style="margin: 5px 0 15px 0; font-size: 2.5rem;">Clinical Reports Database</h1>
    <p style="font-size: 1rem; color: #94a3b8; max-width: 800px;">
        Browse, search, and download archived PDF medical reports generated by the Neural Shield AI system.
    </p>
</div>
""", unsafe_allow_html=True)

# Find all reports
report_pattern = os.path.join("reports", "Report_*.pdf")
report_files = glob.glob(report_pattern)

# Also check for the generic final report if no individual reports exist
has_generic = os.path.exists("reports/final_medical_report.pdf")

if not report_files and not has_generic:
    st.markdown("""
    <div class="premium-card" style="text-align: center; padding: 50px 20px;">
        <div style="font-size: 50px; color:#64748b; margin-bottom:15px;"><i class="fa-solid fa-folder-open"></i></div>
        <h4 style="color:#f8fafc; margin-bottom:10px;">No Diagnostic Reports Archived</h4>
        <p style="color:#64748b; max-width: 500px; margin: 0 auto 20px auto;">
            Run a patient image analysis inside the "Run Analysis" section first to generate and save reports automatically.
        </p>
    </div>
    """, unsafe_allow_html=True)
else:
    # Search Filter
    search_query = st.text_input("🔍 Search reports by Patient Name:")
    
    # Process files list
    records = []
    
    for filepath in report_files:
        filename = os.path.basename(filepath)
        # Pattern: Report_PatientName_ID.pdf
        parts = filename.replace("Report_", "").replace(".pdf", "").split("_")
        
        # Reconstruct name and ID
        if len(parts) >= 2:
            report_id = parts[-1]
            patient_name = " ".join(parts[:-1])
        else:
            patient_name = filename
            report_id = "N/A"
            
        mtime = os.path.getmtime(filepath)
        date_str = datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S")
        size_kb = os.path.getsize(filepath) / 1024
        
        records.append({
            "name": patient_name,
            "id": report_id,
            "date": date_str,
            "size": f"{size_kb:.1f} KB",
            "path": filepath
        })
        
    # Sort by date descending
    records = sorted(records, key=lambda x: x["date"], reverse=True)
    
    # Filter records by search query
    if search_query:
        records = [r for r in records if search_query.lower() in r["name"].lower()]
        
    if not records:
        if has_generic and not search_query:
            # Only final_medical_report exists
            st.info("Showing default latest report. Individual patient records are empty.")
            with open("reports/final_medical_report.pdf", "rb") as f:
                st.download_button(
                    "Download Latest Clinical Report",
                    f,
                    file_name="latest_facial_paralysis_report.pdf",
                    mime="application/pdf"
                )
        else:
            st.warning("No reports found matching your search term.")
    else:
        st.markdown(f"**Found {len(records)} archived patient reports:**")
        
        for idx, rec in enumerate(records):
            # Display each record inside a nice grid or custom card
            col_info, col_download = st.columns([4, 1])
            
            with col_info:
                st.markdown(f"""
                <div style="background: rgba(31, 41, 55, 0.4); border: 1px solid rgba(255, 255, 255, 0.05); border-radius: 12px; padding: 15px; margin-bottom: 10px; display:flex; justify-content:space-between; align-items:center;">
                    <div>
                        <div style="font-weight:700; color:#f8fafc; font-size:1.1rem;"><i class="fa-solid fa-file-pdf" style="color:#ef4444; margin-right:8px;"></i> {rec['name']}</div>
                        <div style="font-size:0.8rem; color:#64748b; margin-top:4px;">Report ID: {rec['id']} • Generated: {rec['date']} • Size: {rec['size']}</div>
                    </div>
                </div>
                """, unsafe_allow_html=True)
                
            with col_download:
                st.markdown("<div style='margin-top: 10px;'></div>", unsafe_allow_html=True)
                with open(rec["path"], "rb") as f:
                    st.download_button(
                        label="Download PDF",
                        data=f,
                        file_name=os.path.basename(rec["path"]),
                        mime="application/pdf",
                        key=f"dl_{idx}"
                    )
